import pandas as pd
import streamlit as st

from components import cards, layout, tables
from data.mock_data import RISK_CLUSTERS, RISK_FILTERS, RISK_STATS


def _filtered(rows, chip, query):
    out = rows
    if chip.startswith(">85%"):
        out = [r for r in out if r["score"] > 85]
    elif chip == "Phantom Billing":
        out = [r for r in out if r["typology"][0] == "Phantom Billing"]
    elif chip == "Repeat Billing":
        out = [r for r in out if r["typology"][0] == "Repeat Billing"]
    if query:
        q = query.lower()
        out = [r for r in out if q in r["name"].lower() or q in r["subtitle"].lower() or q in r["id"].lower()]
    return out


def render():
    right = (
        '<div style="display:flex;gap:8px;justify-content:flex-end;">'
        '<span class="j-chip">⚙ Threshold: &gt;85% High Impact</span></div>'
    )
    layout.page_header(
        "", "teal", "Risk Ranking",
        "Ranked by Network Risk Score from graph cluster analysis — entities above 85% are auto-flagged "
        "for review.",
        right_html=right,
    )
    st.markdown(
        '<div style="margin:-26px 0 14px 0;"><span class="j-pill teal">HIN Anomaly Prioritization</span></div>',
        unsafe_allow_html=True,
    )
    _all = pd.DataFrame([{k: (v if not isinstance(v, tuple) else v[0]) for k, v in c.items()}
                         for c in RISK_CLUSTERS])
    st.download_button("⬇ Ekspor Bukti Audit", _all.to_csv(index=False).encode("utf-8"),
                       file_name="jala_bukti_audit.csv", type="primary", key="export_top")

    cols = st.columns(4)
    for col, s in zip(cols, RISK_STATS):
        with col:
            st.markdown(
                f'<div class="j-card">{cards.stat_card(s["label"], s["value"], s["note"], s["icon"], s["icon_tone"], s["tone"])}</div>',
                unsafe_allow_html=True,
            )

    st.markdown('<div style="height:14px"></div>', unsafe_allow_html=True)
    f1, f2 = st.columns([2, 3])
    with f1:
        query = st.text_input("q", placeholder="Search Entity ID, Ring Name, Faskes…  ⌘K",
                              label_visibility="collapsed")
    with f2:
        chip = st.session_state.get("risk_chip", RISK_FILTERS[0])
        cols = st.columns(len(RISK_FILTERS))
        for col, label in zip(cols, RISK_FILTERS):
            with col:
                if st.button(label, key=f"chip_{label}", width="stretch",
                             type="primary" if label == chip else "secondary"):
                    st.session_state.risk_chip = label
                    st.rerun()

    rows = _filtered(RISK_CLUSTERS, chip, query)
    with st.container(border=True):
        if rows:
            st.markdown(tables.risk_table_html(rows), unsafe_allow_html=True)
        else:
            st.info("Tidak ada klaster yang cocok dengan filter/pencarian.")

    st.markdown(
        """
        <div class="j-footer" style="margin-top:14px;">
          <div>✅ Showing all prioritized clusters generated by Graph Engine v2.4 Louvain partition</div>
          <div>Cycle ID: #2024Q3-LOUVAIN-08 &nbsp;•&nbsp; Confidence Interval: 99.2%</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown('<div style="height:16px"></div>', unsafe_allow_html=True)
    a1, a2, a3, a4 = st.columns([2, 1, 1, 1])
    with a1:
        names = {c["name"]: c["id"] for c in RISK_CLUSTERS}
        picked = st.selectbox("Pilih klaster", list(names.keys()), label_visibility="collapsed",
                              key="risk_pick")
    with a2:
        if st.button("Buka Claim Details", width="stretch", type="primary"):
            layout.goto("claim", cluster=names[picked])
    with a3:
        if st.button("Lihat Sub-Graph", width="stretch"):
            layout.goto("network")
    with a4:
        df = pd.DataFrame([{k: (v if not isinstance(v, tuple) else v[0]) for k, v in c.items()} for c in rows])
        st.download_button("⬇ CSV", df.to_csv(index=False).encode("utf-8"),
                           file_name="jala_risk_ranking.csv", width="stretch")

    layout.render_footer()
