[theme]
base = "light"
primaryColor = "#0F766E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#132A1C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
